# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Chang
email: cht8687@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  React advocator! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cht8687.github.io" # the base hostname & protocol for your site
twitter_username: cht0001
github_username:  cht8687

# Build settings
markdown: kramdown
